-- AlterTable
ALTER TABLE "Agent" ADD COLUMN "emotion" DOUBLE PRECISION DEFAULT 0.667;
ALTER TABLE "Agent" ADD COLUMN "stability" DOUBLE PRECISION DEFAULT 0.8;
ALTER TABLE "Agent" ADD COLUMN "reasoningMode" BOOLEAN DEFAULT false;
